### PR TITLE
[BD] Modernize analyticsdataserver/ 

### PR DESCRIPTION
**Pull request by morenol**
### Description
https://openedx.atlassian.net/browse/BOM-1359
Modernize analyticsdataserver with the following commands:

- python-modernize -w analyticsdataserver
- isort -rc analyticsdataserver

It was changed the isort configs in the setup.cfg (this config was also used in the other PRs and it is based on the edx-platform configs)

## Reviewers
- [x] @andrey-canon
- [x] Is this ready for edX's review?
- [ ] @jmbowman

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-4147](https://openedx.atlassian.net/browse/OSPR-4147) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by andrey-canon** [comment]
@morenol  LGTM

**Comment by natabene** [comment]
@jmbowman This is ready for your review.

**Comment by edx-webhook** [comment]
@morenol 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-data-api&entry.867055334=https://github.com/edx/edx-analytics-data-api/pull/305&entry.1484655318=https://github.com/morenol&entry.752974735=2020-03-02+23:10&entry.1917517419=2020-03-03+17:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
