### PR TITLE
Run unit tests against real elasticsearch

### PR DESCRIPTION
**Pull request by dan-f**
Also removes the 'problem_attempts' field from the roster entry, since
there's no defined use case.

AN-6151

### CODE REVIEW

**Comment by dan-f** [comment]
@dsjen please review

**Comment by dsjen** [comment]
@dan-f this is fantastic!  I run into a an `IndexAlreadyExistsException` when running locally though.  Are you seeing that with `make test`?

**Comment by dan-f** [comment]
@dsjen that shouldn't happen... the test is supposed to delete the index at the end of the test. Are you positive that you're testing against test settings? e.g. `ELASTICSEARCH_LEARNERS_HOST` should be `'http://localhost:9200/'`.

**Comment by dsjen** [comment]
I see.  I was running against the test settings, but I hadn't run `make test.install_elasticsearch` and `make test.run_elasticsearch`.  After doing that, tests pass.

Could we add elastic search start up and shut down when running `make test`?  It seems like it would also be advantageous to add `test.install_elasticsearch` to the `test.requirements` step too, but I'm not sure how easy it is to detect if elasticsearch has been downloaded.

**Comment by dan-f** [comment]
I see. I think I can write `test.instsall_elasticsearch` such that it only installs if it hasn't already been installed on the system.

**Comment by dan-f** [comment]
It turns out that testing for elasticsearch and automating it's start up are a little trickier than I initially thought. To test for elasticsearch or run it (as a system service), you need sudo privileges, which travis doesn't give us. Automating elasticsearch's startup is difficult because it takes a nondeterministic amount of time. I hacked around that with Travis' suggestion of putting a 'sleep 10' in the .travis.yml, but I don't like the idea of adding that to the makefile. How about I document in the README that ES must be running locally for tests to run? Once you start the ES server as a daemon, you can forget about it, rather than start and restart every time tests run. This is the approach that the [edx-notes-api](https://github.com/edx/edx-notes-api) takes.

**Comment by dsjen** [comment]
@dan-f -- thanks for investigating that!  Adding documentation to the README sounds good to me.

**Comment by dan-f** [comment]
Updated @dsjen!

**Comment by dsjen** [comment]
Beautiful! :+1:

**Pull request merged**
