### PR TITLE
Learner analytics

### PR DESCRIPTION
**Pull request by dan-f**
[AN-6954](https://openedx.atlassian.net/browse/AN-6954)

@dsjen

### CODE REVIEW

**Comment by dan-f** [comment]
Sad that coverage decreased. @dsjen are you familiar with coveralls? Perhaps we can find the lines of code that were missed and make the call whether they're worth testing or not.

**Comment by dsjen** [comment]
That is too bad!  I'm not too familiar with coveralls unfortunately.  It does look like https://coveralls.io/builds/5719892 dissects it a bit more.  It looks like better coverage of utils might do the trick.

**Comment by dsjen** [comment]
It's my sense that coverage is pretty good still, so this LGTM still.  It's up to you!

**Comment by dan-f** [comment]
I'm going to check the coverage issue tomorrow morning, but I'll timebox it. I don't understand how coverage for `utils.py` is reported down 50% when it clearly increased on the branch...

**Comment by dan-f** [comment]
^ 👏  ^

**Comment by dsjen** [comment]
:+1: Wonderful!

**Pull request merged**
