### PR TITLE
Adds the cumulative_count response

### PR DESCRIPTION
**Pull request by lamagnifica**
@dsjen @shnayder please check the updated wording for the responses. @dsjen also please confirm that this new response is publicly available now.
@mhoeber please check everything! first API doc update...

### CODE REVIEW

**Comment by dsjen** [comment]
:+1: The copy looks good to me.  The one item of note is that the line breaks translate to new lines in the online API documentation too:

screen shot 2015-06-25 at 2 01 06 pm

I don't have a problem with it (it's perfectly readable), but just wanted to make sure you know of the side effect.

Also, the API isn't deployed yet.  We would need changes to the data at the same time as this is released.

**Comment by lamagnifica** [comment]
@dsjen I did not know that -- it's fairly automatic for me to wrap line is rst files. Will do my best to fight the urge in py files!

**Comment by dsjen** [comment]
@lamagnifica -- no problem!  I actually don't have a preference for it be wrapped or not.  The other ones currently aren't, so I suppose that's the convention thus far.

**Comment by dsjen** [comment]
@lamagnifica -- are you ok to merge this in?

**Comment by mhoeber** [comment]
:+1:   looks good to me.  can you update change log date?

**Comment by shnayder** [comment]
looks good

**Comment by lamagnifica** [comment]
@dsjen I updated the change log date to tomorrow (5 Aug) per estimate this morning and squashed. All tests pass, so this is ready to merge and publish when the release goe sout.

**Comment by dsjen** [comment]
@lamagnifica Thank you!

**Comment by lamagnifica** [comment]
@dsjen good heavens, this still isn't merged! Should I go ahead? any concerns or need to check anything before I do?

**Comment by dsjen** [comment]
Looks good to me!  Please feel free to merge.

**Pull request merged**
