### PR TITLE
BOM-1623 : Python 3.8 support

### PR DESCRIPTION
**Pull request by mzulqarnain1**

### CODE REVIEW

**Comment by morenol** [comment]
In the past I had to make this change to add the python 3.5 interpreter to the docker container and run the tests in that version of python https://github.com/edx/configuration/pull/5692

Will we do the same again? or will we use the dockerfile of this repo?

**Comment by mzulqarnain1** [comment]
> In the past I had to make this change to add the python 3.5 interpreter to the docker container and run the tests in that version of python [edx/configuration#5692](https://github.com/edx/configuration/pull/5692)
> 
> Will we do the same again? or will we use the dockerfile of this repo?
> 
> We have the same problem in other repos, insights, ecommerce...

Hey, @morenol I'm not quite sure yet myself about what we have to do here, but also I don't think we would have to change anything in configuration repo. I am looking into it currently.

**Comment by morenol** [comment]
@mzulqarnain1 

Maybe we can try to install python 3.8 every time that we are running the tests, so we don't get blocked by that. And then once that is solved in the base image used we can remove that.

I tried running this on the docker container:

    sudo add-apt-repository ppa:deadsnakes/ppa -y;
    sudo apt-get update -y;
    sudo apt-get install python3.8 python3.8-distutils -y;"

https://github.com/edx/ecommerce/pull/2943/

**Comment by mzulqarnain1** [comment]
> @mzulqarnain1
> 
> Maybe we can try to install python 3.8 every time that we are running the tests, so we can start to work in the real problems and do not get blocked by that.
> 
> And then once that is solved in the base image used we can remove that.
> 
> I tried running this on the docker container:
> 
> ```
> sudo add-apt-repository ppa:deadsnakes/ppa -y;
> sudo apt-get update -y;
> sudo apt-get install python3.8 python3.8-distutils -y;"
> ```
> 
> [edx/ecommerce#2943](https://github.com/edx/ecommerce/pull/2943)

@morenol you are right, imo this is a good workaround for the time being. thanks.

**Comment by morenol** [comment]
@mzulqarnain1 other of the packages that we need to install in this one: 

`python3.8-dev`

**Comment by morenol** [comment]
LGTM, but I am not sure if we should merge this or wait for the moment when python 3.8 is installed by default in the docker images.

**Comment by mzulqarnain1** [comment]
> LGTM, but I am not sure if we should merge this or wait for the moment when python 3.8 is installed by default in the docker images.

@jmbowman What is your opinion about this?

**Comment by morenol** [comment]
@mzulqarnain1 I think that we don't need to install the python 3.8 anymore since [now](https://github.com/edx/configuration/pull/5791) the base image of docker has installed the python 3.8 packages.

We need to check if the last version of the image used in the tests in this rep ohas that changes https://hub.docker.com/r/edxops/analytics_api.

In ecommerce the image was updated https://github.com/edx/ecommerce/pull/2943.

**Comment by mzulqarnain1** [comment]
> @mzulqarnain1 I think that we don't need to install the python 3.8 anymore since [now](https://github.com/edx/configuration/pull/5791) the base image of docker has installed the python 3.8 packages.
> 
> We need to check if the last version of the image used in the tests in this rep ohas that changes https://hub.docker.com/r/edxops/analytics_api.
> 
> In ecommerce the image was updated [edx/ecommerce#2943](https://github.com/edx/ecommerce/pull/2943).

Great, let me remove and test.

**Pull request merged**
