### PR TITLE
[BD] Upgrade django to Django 2.2

### PR DESCRIPTION
**Pull request by morenol**
## Description

Upgrade to django 2.2

## Reviewers
- [ ] @andrey-canon
- [x] Ready for edX review
- [ ] @jmbowman

### CODE REVIEW

**Comment by morenol** [comment]
Current warnings in Django 2.2 version: 383
From which 318 are ResourceWarning: unclosed <socket... with the elasticsearch test container.\

**Comment by morenol** [comment]
@jmbowman Here I removed the constraint to django-waffle which is meant to remove the support for django <2.2. Should I remove the other tests? or should I add the constraint to django-waffle?

**Comment by jmbowman** [comment]
@morenol - no, let's keep those for now.  Can delete after this has been running on prod for a little while without needing to roll it back.

**Comment by edx-webhook** [comment]
Although this pull request is already merged, I've created [OSPR-5387](https://openedx.atlassian.net/browse/OSPR-5387) so that we can track it in Jira.

There is nothing you have to do. No action is needed from your side.  Thanks again for your contribution.

**Pull request merged**
