### PR TITLE
Removed milliseconds from created date in problems endpoint.

### PR DESCRIPTION
**Pull request by dsjen**

### CODE REVIEW

**Comment by dsjen** [comment]
@jab5569 @mulby @brianhw -- Including the milliseconds was causing errors when loading the answer distribution fixture.

**Comment by mulby** [comment]
was this never working?

**Comment by dsjen** [comment]
At some point, loading the fixtures was working.  It must have broke when the `if not isinstance(created, datetime.datetime):` code was added in.

**Comment by jab5569** [comment]
I verified these strftime commands as you have them in test_courses.py in the python command line. 

GTM. :+1:

**Pull request merged**
