### PR TITLE
[BD] Upgrade edx-drf-extensions

### PR DESCRIPTION
**Pull request by morenol**
### Description

Related to https://openedx.atlassian.net/browse/BOM-1359

This upgrade was already merged in https://github.com/edx/edx-analytics-data-api/pull/316, but since @jmbowman  mentioned in https://github.com/edx/edx-analytics-dashboard/pull/964#pullrequestreview-372655982 we need to change this setting.

## Reviewers
 - [x] @andrey-canon
 - [x] Is this ready for edX's review?
- [ ] @jmbowman

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-4199](https://openedx.atlassian.net/browse/OSPR-4199) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by andrey-canon** [comment]
@morenol  you are including the changes of this pr in https://github.com/edx/edx-analytics-data-api/pull/325

**Comment by morenol** [comment]
> @morenol you are including the changes of this pr in #325

Yes, I was doing that PR, and noticed that the version changed. So I thought that it would be better seperate the PRs.

For that reason I am waiting for this PR to get merged and then rebase the other one.

**Comment by andrey-canon** [comment]
@morenol LGTM

**Comment by morenol** [comment]
I wonder if this needs to be added also to your analytics_api.yml configurations.

**Pull request merged**
