### PR TITLE
Version bump for edx-enterprise-data to 1-0-5

### PR DESCRIPTION
**Pull request by irfanuddinahmad**
Version bump for edx-enterprise-data to 1-0-5

### CODE REVIEW

**Comment by asadiqbal08** [comment]
@irfanuddinahmad Can you please confirm that either we need to update the versions in `.txt files` or in `.in ones` ? The [Text](https://github.com/edx/edx-analytics-data-api/pull/225/files#diff-7fe11226cff646f5d9f35faa76217059R2) in each file show me it is an auto generated file by pip-compile

**Comment by irfanuddinahmad** [comment]
> @irfanuddinahmad Can you please confirm that either we need to update the versions in `.txt files` or in `.in ones` ? The [Text](https://github.com/edx/edx-analytics-data-api/pull/225/files#diff-7fe11226cff646f5d9f35faa76217059R2) in each file show me it is an auto generated file by pip-compile

@asadiqbal08 The edx-enterprise-data is already added to the base.in file, hence, only .txt files are part of this PR

**Comment by asadiqbal08** [comment]
👍

**Comment by georgebabey** [comment]
Can close this in favor of #226

**Comment by irfanuddinahmad** [comment]
Closing in favor of #226

**Pull request closed without merging**
