### PR TITLE
Update requirements.txt for Analytics API documentation builds - DOC-2538

### PR DESCRIPTION
**Pull request by pdesjardins**
## [DOC-2538](https://openedx.atlassian.net/browse/DOC-2538)

The API documentation in edx-analytics-data-api/docs/api is the source for this external document:

  http://edx.readthedocs.org/projects/edx-data-analytics-api/en/latest/index.html

Local builds have been failing because of failure to import required modules. With help from Dennis Jen, I fixed the import failures by installing the packages in requirements/base.txt. Now the requirements.txt file in the docs/api directory imports requirements/base.txt as well as requirements/doc.txt

### Reviewers

- [x] Subject matter expert: @dsjen  
- [ ] Doc team review (sanity check/copy edit/dev edit): @lamagnifica 

### HTML Version
- [x] http://draft-analytics-api-doc.readthedocs.org/
 
### Post-review
- [ ] Squash commits

### CODE REVIEW

**Comment by pdesjardins** [comment]
More context: the RTD build for this documentation has not run in 3.5 months:

  https://readthedocs.org/projects/edx-data-analytics-api/builds/

So the document is not broken on RTD right now, but I suspect it will since local builds of master are failing.

**Comment by dsjen** [comment]
LGTM! :+1:

**Comment by lamagnifica** [comment]
@pdesjardins what is the best way for me to verify this?

**Comment by pdesjardins** [comment]
Something like:

git clone https://github.com/edx/edx-analytics-data-api.git
cd cd edx-analytics-data-api/docs/api
sudo -H pip install -r requirements.txt (WARNING: this alters your laptop Python package versions, which I don't mind personally)
make html

You should see a long list of errors in the build, and many of the resulting HTML pages will have missing docstring content.

git checkout pdesjardins/DOC-2538
sudo -H pip install -r requirements.txt
make html

The errors should be gone. The resulting HTML files should have the expected docstring content.

**Comment by lamagnifica** [comment]
:+1: 
yay!

**Pull request merged**
