### PR TITLE
upgrade edx-enterprise-data 2.2.21

### PR DESCRIPTION
**Pull request by muhammad-ammar**
**Description:** This releases the changes that we have made in https://github.com/edx/edx-enterprise-data/pull/260

**JIRA:** https://openedx.atlassian.net/browse/ENT-4506

### CODE REVIEW

**Review by HammadAhmadWaqas — APPROVED** [review]
Please follow the conventional commits and PR title, otherwise looks good.

**Comment by muhammad-ammar** [comment]
> Please follow the conventional commits and PR title, otherwise looks good.

@HammadAhmadWaqas @saleem-latif  Should this commit be a `chore` or `feat`? My understanding is that this is a `chore` here and `feat` in the edx-enterprise-data. Also how do you suggest the title format should be?

**Comment by HammadAhmadWaqas** [comment]
@muhammad-ammar yes it should be `chore`. 
and title could be: 
Chore: Upgrade edx-enterprise-data 2.2.21

see this [docs](https://open-edx-proposals.readthedocs.io/en/latest/oep-0051-bp-conventional-commits.html) for more details.

**Review by schenedx — APPROVED** [review]
👍

**Comment by schenedx** [comment]
@muhammad-ammar Just make sure we are aligned. You can merge and deploy the analytics-data-api service through GoCD yourself right?

**Comment by muhammad-ammar** [comment]
> @muhammad-ammar Just make sure we are aligned. You can merge and deploy the analytics-data-api service through GoCD yourself right?

@schenedx Yes, I can merge and then deploy it through GoCD.

**Pull request merged**
